### ISSUE TITLE
Nextcloud client 2.3 crash on KDE: Segmentation fault

### ISSUE THREAD

**Issue by nemobis** [nextcloud/desktop#1099]
Might be the same as issue #1088 and issue #441, or not. Segmentation fault on Fedora 29 with KDE, Plasma version 5.14.4. 
```
$ nextcloud --version
Nextcloud version 2.3.3
Git revision 57bc7918d7b0650c116f3512787f7677d4e5ab17
Using Qt 5.11.3, built against Qt 5.9.1
Using 'OpenSSL 1.1.1a FIPS  20 Nov 2018'
$ rpm -qa | grep nextcloud
nextcloud-client-libs-2.3.3-2.fc28.x86_64
nextcloud-client-2.3.3-2.fc28.x86_64
$ uname -a
Linux a88x 4.19.7-300.fc29.x86_64 #1 SMP Wed Dec 5 22:21:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

ABRT gives:

```
Application: nextcloud (nextcloud), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fa7a7f8ce40 (LWP 5142))]

Thread 16 (Thread 0x7fa774ff9700 (LWP 2735)):
#0  0x00007fa7a6cbeb28 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa7a79b2865 in QWaitCondition::wait(QMutex*, unsigned long) () at /lib64/libQt5Core.so.5
#2  0x00007fa7a79aab12 in  () at /lib64/libQt5Core.so.5
#3  0x00007fa7a79b22fb in  () at /lib64/libQt5Core.so.5
#4  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#5  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 15 (Thread 0x7fa775ffb700 (LWP 2734)):
[KCrash Handler]
#6  0x00007fa7a7e820e8 in  () at /lib64/libQt5Network.so.5
#7  0x00007fa7a7e80a39 in  () at /lib64/libQt5Network.so.5
#8  0x00007fa7a7b6ada6 in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#9  0x00007fa7a85f5285 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#10 0x00007fa7a85fc9a0 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#11 0x00007fa7a7b41ec6 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#12 0x00007fa7a7b4509b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#13 0x00007fa7a7b92807 in  () at /lib64/libQt5Core.so.5
#14 0x00007fa7a564706d in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#15 0x00007fa7a5647438 in  () at /lib64/libglib-2.0.so.0
#16 0x00007fa7a56474d0 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#17 0x00007fa7a7b92593 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#18 0x00007fa7a7b40e0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#19 0x00007fa7a79a8e86 in QThread::exec() () at /lib64/libQt5Core.so.5
#20 0x00007fa7a79b22fb in  () at /lib64/libQt5Core.so.5
#21 0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#22 0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 14 (Thread 0x7fa7767fc700 (LWP 2733)):
#0  0x00007fa7a6cbeb28 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa7a79b2865 in QWaitCondition::wait(QMutex*, unsigned long) () at /lib64/libQt5Core.so.5
#2  0x00007fa7a79aab12 in  () at /lib64/libQt5Core.so.5
#3  0x00007fa7a79b22fb in  () at /lib64/libQt5Core.so.5
#4  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#5  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 13 (Thread 0x7fa7757fa700 (LWP 5208)):
#0  0x00007fa7a79a5d13 in QMutex::unlock() () at /lib64/libQt5Core.so.5
#1  0x00007fa7a7b924c1 in  () at /lib64/libQt5Core.so.5
#2  0x00007fa7a56468e9 in g_main_context_prepare () at /lib64/libglib-2.0.so.0
#3  0x00007fa7a56472db in  () at /lib64/libglib-2.0.so.0
#4  0x00007fa7a56474d0 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#5  0x00007fa7a7b925ab in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#6  0x00007fa7a7b40e0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#7  0x00007fa7a79a8e86 in QThread::exec() () at /lib64/libQt5Core.so.5
#8  0x00007fa7a79b22fb in  () at /lib64/libQt5Core.so.5
#9  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#10 0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 12 (Thread 0x7fa7777fe700 (LWP 5194)):
#0  0x00007fa7a6cbe73c in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa78a663c03 in  () at /usr/lib64/dri/radeonsi_dri.so
#2  0x00007fa78a66395b in  () at /usr/lib64/dri/radeonsi_dri.so
#3  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#4  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 11 (Thread 0x7fa777fff700 (LWP 5193)):
#0  0x00007fa7a6cbe73c in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa78a663c03 in  () at /usr/lib64/dri/radeonsi_dri.so
#2  0x00007fa78a66395b in  () at /usr/lib64/dri/radeonsi_dri.so
#3  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#4  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 10 (Thread 0x7fa784b64700 (LWP 5192)):
#0  0x00007fa7a6cbe73c in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa78a663c03 in  () at /usr/lib64/dri/radeonsi_dri.so
#2  0x00007fa78a66395b in  () at /usr/lib64/dri/radeonsi_dri.so
#3  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#4  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 9 (Thread 0x7fa785365700 (LWP 5191)):
#0  0x00007fa7a6cbe73c in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa78a663c03 in  () at /usr/lib64/dri/radeonsi_dri.so
#2  0x00007fa78a66395b in  () at /usr/lib64/dri/radeonsi_dri.so
#3  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#4  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 8 (Thread 0x7fa785b66700 (LWP 5190)):
#0  0x00007fa7a6cbe73c in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa78a663c03 in  () at /usr/lib64/dri/radeonsi_dri.so
#2  0x00007fa78a66395b in  () at /usr/lib64/dri/radeonsi_dri.so
#3  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#4  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 7 (Thread 0x7fa786367700 (LWP 5189)):
#0  0x00007fa7a6cbe73c in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa78a663c03 in  () at /usr/lib64/dri/radeonsi_dri.so
#2  0x00007fa78a66395b in  () at /usr/lib64/dri/radeonsi_dri.so
#3  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#4  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7fa786cc7700 (LWP 5188)):
#0  0x00007fa7a6cbe73c in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa78a663c03 in  () at /usr/lib64/dri/radeonsi_dri.so
#2  0x00007fa78a66395b in  () at /usr/lib64/dri/radeonsi_dri.so
#3  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#4  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7fa798ede700 (LWP 5146)):
#0  0x00007fa7a79a5d13 in QMutex::unlock() () at /lib64/libQt5Core.so.5
#1  0x00007fa7a7b924c1 in  () at /lib64/libQt5Core.so.5
#2  0x00007fa7a56468e9 in g_main_context_prepare () at /lib64/libglib-2.0.so.0
#3  0x00007fa7a56472db in  () at /lib64/libglib-2.0.so.0
#4  0x00007fa7a56474d0 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#5  0x00007fa7a7b925ab in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#6  0x00007fa7a7b40e0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#7  0x00007fa7a79a8e86 in QThread::exec() () at /lib64/libQt5Core.so.5
#8  0x00007fa7a79b22fb in  () at /lib64/libQt5Core.so.5
#9  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#10 0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7fa7996df700 (LWP 5145)):
#0  0x00007fa7abdcff84 in __tls_get_addr () at /lib64/ld-linux-x86-64.so.2
#1  0x00007fa7a79b173a in  () at /lib64/libQt5Core.so.5
#2  0x00007fa7a7b9248e in  () at /lib64/libQt5Core.so.5
#3  0x00007fa7a5646dc1 in g_main_context_check () at /lib64/libglib-2.0.so.0
#4  0x00007fa7a5647350 in  () at /lib64/libglib-2.0.so.0
#5  0x00007fa7a56474d0 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#6  0x00007fa7a7b925ab in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#7  0x00007fa7a7b40e0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#8  0x00007fa7a79a8e86 in QThread::exec() () at /lib64/libQt5Core.so.5
#9  0x00007fa7abc9ff89 in  () at /lib64/libQt5DBus.so.5
#10 0x00007fa7a79b22fb in  () at /lib64/libQt5Core.so.5
#11 0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#12 0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7fa79b777700 (LWP 5144)):
#0  0x00007fa7a6dca421 in poll () at /lib64/libc.so.6
#1  0x00007fa7a352d39f in  () at /lib64/libxcb.so.1
#2  0x00007fa7a352f01a in xcb_wait_for_event () at /lib64/libxcb.so.1
#3  0x00007fa79b802bf9 in  () at /lib64/libQt5XcbQpa.so.5
#4  0x00007fa7a79b22fb in  () at /lib64/libQt5Core.so.5
#5  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#6  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7fa7a2fbf700 (LWP 5143)):
#0  0x00007fa7a6cbe73c in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007fa7a7105690 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () at /lib64/libstdc++.so.6
#2  0x00007fa7ab0e197a in  () at /lib64/libQt5WebKit.so.5
#3  0x00007fa7ab0e1aaf in  () at /lib64/libQt5WebKit.so.5
#4  0x00007fa7a710b943 in  () at /lib64/libstdc++.so.6
#5  0x00007fa7a6cb858e in start_thread () at /lib64/libpthread.so.0
#6  0x00007fa7a6dd56a3 in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7fa7a7f8ce40 (LWP 5142)):
#0  0x00007ffdd9dfb9b9 in  ()
#1  0x00007ffdd9dfbbbc in clock_gettime ()
#2  0x00007fa7a6de3692 in clock_gettime () at /lib64/libc.so.6
#3  0x00007fa7a7b91db5 in  () at /lib64/libQt5Core.so.5
#4  0x00007fa7a7b9089d in QTimerInfoList::updateCurrentTime() () at /lib64/libQt5Core.so.5
#5  0x00007fa7a7b90ca9 in QTimerInfoList::timerWait(timespec&) () at /lib64/libQt5Core.so.5
#6  0x00007fa7a7b92264 in  () at /lib64/libQt5Core.so.5
#7  0x00007fa7a56468e9 in g_main_context_prepare () at /lib64/libglib-2.0.so.0
#8  0x00007fa7a56472db in  () at /lib64/libglib-2.0.so.0
#9  0x00007fa7a56474d0 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#10 0x00007fa7a7b925ab in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#11 0x00007fa79b896855 in  () at /lib64/libQt5XcbQpa.so.5
#12 0x00007fa7a7b40e0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#13 0x00007fa7a7b48ed6 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#14 0x0000556d1d7a85e3 in main ()
[Inferior 1 (process 5142) detached]
```

**Comment by camilasan** [comment]
Hi @nemobis! Is there a specific reasons for you to use 2.3.3 instead of the latest version?

**Comment by nemobis** [comment]
Camila Ayres, 27/02/19 21:49:
> Hi @nemobis <https://github.com/nemobis>! Is there a specific reasons 
> for you to use 2.3.3 instead of the latest version?

Thanks for asking. It's just the version which was packaged at that 
time. I see fedora 30 will be on 2.5.
https://apps.fedoraproject.org/packages/nextcloud-client

**Comment by camilasan** [comment]
Ok, @nemobis. As soon as you can upgrade, please update the issue if you still have the problem or not :) Thanks.

**Comment by DominiqueFuchs** [comment]
Please continue in #241 if the issue still exists, thanks!
