### ISSUE TITLE
Linux nextcloud client crashes after client autostart after login

### ISSUE THREAD

**Issue by binsky08** [nextcloud/desktop#1167]
### Expected behaviour
user login and autostart of nextcloud-client

### Actual behaviour
nextcloud-client tried to start and crashed

### Steps to reproduce
1. enable Nextcloud (client) autostart
2. reboot & login
3. sometimes it crashes

### Client configuration
Client version: 2.5.2-20190319

Operating system: Debian 10 64-bit

OS language: German

KDE Plasma version: 5.14.5

Qt version used by client package (Linux only, see also Settings dialog): 5.11.3

Client package (From Nextcloud or distro) (Linux only): 2.5.2-20190319.015224
Repository path: https://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0

Installation path of client: /usr/bin/nextcloud

### Server configuration

Operating system: Ubuntu 18.04.2

Web server: nginx

Database: 5.7.25-28-57 - Percona XtraDB Cluster

PHP version: 7.2.15-0

Nextcloud version: 15.0.5

### Error log

```Application: nextcloud (nextcloud), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f7b33a1dd80 (LWP 3604))]

Thread 8 (Thread 0x7f7b137fe700 (LWP 4510)):
[KCrash Handler]
#6  0x00007f7b4126cba4 in QHttpNetworkConnectionChannel::sendRequest (this=<optimized out>) at access/qhttpnetworkconnectionchannel.cpp:251
#7  0x00007f7b4126bc69 in QHttpNetworkConnectionPrivate::_q_startNextRequest (this=0x7f7b00003e00) at access/qhttpnetworkconnection.cpp:1044
#8  0x00007f7b409e5182 in QObject::event (this=0x7f7b000038d0, e=<optimized out>) at kernel/qobject.cpp:1251
#9  0x00007f7b4421d4b1 in QApplicationPrivate::notify_helper (this=this@entry=0x558ae331efe0, receiver=receiver@entry=0x7f7b000038d0, e=e@entry=0x7f7b00004ba0) at kernel/qapplication.cpp:3726
#10 0x00007f7b44224950 in QApplication::notify (this=0x7fff658be0b0, receiver=0x7f7b000038d0, e=0x7f7b00004ba0) at kernel/qapplication.cpp:3485
#11 0x00007f7b409bb5a9 in QCoreApplication::notifyInternal2 (receiver=0x7f7b000038d0, event=0x7f7b00004ba0) at ../../include/QtCore/5.11.3/QtCore/private/../../../../../src/corelib/thread/qthread_p.h:307
#12 0x00007f7b409be59b in QCoreApplication::sendEvent (event=0x7f7b00004ba0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#13 QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x558ae399e450) at kernel/qcoreapplication.cpp:1744
#14 0x00007f7b40a0d233 in postEventSourceDispatch (s=0x7f7b00004fd0) at kernel/qeventdispatcher_glib.cpp:276
#15 0x00007f7b3fe42f2e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f7b3fe431c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f7b3fe4325c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f7b40a0c863 in QEventDispatcherGlib::processEvents (this=0x7f7b00000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#19 0x00007f7b409ba27b in QEventLoop::exec (this=this@entry=0x7f7b137fd820, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#20 0x00007f7b40809ec6 in QThread::exec (this=<optimized out>) at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#21 0x00007f7b40813aa7 in QThreadPrivate::start (arg=0x558ae3a560a0) at thread/qthread_unix.cpp:367
#22 0x00007f7b40253fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#23 0x00007f7b4036682f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 7 (Thread 0x7f7b21b62700 (LWP 4244)):
#0  0x00007f7b4035bb69 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f7b3fe43136 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f7b3fe4325c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f7b40a0c87b in QEventDispatcherGlib::processEvents (this=0x7f7b08000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#4  0x00007f7b409ba27b in QEventLoop::exec (this=this@entry=0x7f7b21b61820, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#5  0x00007f7b40809ec6 in QThread::exec (this=<optimized out>) at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#6  0x00007f7b40813aa7 in QThreadPrivate::start (arg=0x558ae37d2ec0) at thread/qthread_unix.cpp:367
#7  0x00007f7b40253fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f7b4036682f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7f7b23fff700 (LWP 3726)):
#0  0x00007f7b3fe8ce69 in g_mutex_lock () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f7b3fe42675 in g_main_context_prepare () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f7b3fe4306b in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f7b3fe4325c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f7b40a0c87b in QEventDispatcherGlib::processEvents (this=0x7f7b14000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#5  0x00007f7b409ba27b in QEventLoop::exec (this=this@entry=0x7f7b23ffe820, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#6  0x00007f7b40809ec6 in QThread::exec (this=<optimized out>) at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#7  0x00007f7b40813aa7 in QThreadPrivate::start (arg=0x558ae3693bb0) at thread/qthread_unix.cpp:367
#8  0x00007f7b40253fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007f7b4036682f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7f7b28e5e700 (LWP 3725)):
#0  0x00007f7b3fe40065 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f7b3fe42a3f in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f7b3fe430e0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f7b3fe4325c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f7b40a0c87b in QEventDispatcherGlib::processEvents (this=0x7f7b1c000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#5  0x00007f7b409ba27b in QEventLoop::exec (this=this@entry=0x7f7b28e5d7f0, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#6  0x00007f7b40809ec6 in QThread::exec (this=<optimized out>) at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#7  0x00007f7b4c108545 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#8  0x00007f7b40813aa7 in QThreadPrivate::start (arg=0x7f7b4c188d60) at thread/qthread_unix.cpp:367
#9  0x00007f7b40253fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007f7b4036682f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7f7b2aa00700 (LWP 3716)):
#0  0x00007f7b4025a00c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f7b2b03ce63 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#2  0x00007f7b2b03cbb7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#3  0x00007f7b40253fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007f7b4036682f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7f7b32079700 (LWP 3697)):
#0  0x00007f7b4035bb69 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f7b3f2e8cf7 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f7b3f2ea91a in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f7b32b4fd79 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f7b40813aa7 in QThreadPrivate::start (arg=0x558ae3339220) at thread/qthread_unix.cpp:367
#5  0x00007f7b40253fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f7b4036682f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f7b33a17700 (LWP 3693)):
#0  0x00007f7b4025a00c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f7b406833bc in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f7b435d2cf2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#3  0x00007f7b435d2e09 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#4  0x00007f7b40688b2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f7b40253fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f7b4036682f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f7b33a1dd80 (LWP 3604)):
#0  0x00007f7b40357794 in read () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f7b3fe88aa0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f7b3fe42c0f in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f7b3fe430e0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f7b3fe4325c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f7b40a0c87b in QEventDispatcherGlib::processEvents (this=0x558ae33770f0, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#6  0x00007f7b32be63e1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#7  0x00007f7b409ba27b in QEventLoop::exec (this=this@entry=0x7fff658bdfc0, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#8  0x00007f7b409c2262 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#9  0x0000558ae2570c65 in main (argc=<optimized out>, argv=<optimized out>) at ./src/gui/main.cpp:167
[Inferior 1 (process 3604) detached]
```

**Comment by paveldvorak5** [comment]
every time I resume computer from sleep, the client crashes
so my data are not backed up when I forget to start it again

**Comment by jocull** [comment]
> every time I resume computer from sleep, the client crashes
> so my data are not backed up when I forget to start it again

I think this is the same problem that I am having. I have a crash log but am having a hard time narrowing it down. I am on Pop_OS! 19.04 (which is based on Ubuntu)
