### ISSUE TITLE
traps: nextcloud general protection fault

### ISSUE THREAD

**Issue by wrighrc** [nextcloud/desktop#1311]
My nextcloud desktop client has started seg faulting.   I have verified that the seg faults occur under the standard ubuntu kernel and also the 5.1.12 kernel, which prints trap messages now it seems. 

[nextcloud-sysinfo.txt](https://github.com/nextcloud/desktop/files/3317098/nextcloud-sysinfo.txt)
[nextcloud-strace.txt](https://github.com/nextcloud/desktop/files/3317099/nextcloud-strace.txt)
[nextcloud-traps.txt](https://github.com/nextcloud/desktop/files/3317100/nextcloud-traps.txt)

**Comment by wrighrc** [comment]
I figured out that what was making it crash.

I removed this hidden/tmp file to get past the issue.

2003-corolla-crash-court/2019-04-04-Police-Footage/.19012730_Spofford_redacted.mp4.~17a3fb8

Here the end of the log file just before seg fault.

charles@x360:/scratch$ tail -n5 nextcloud-clientlog2
[OCC::PropagateItemJob::done 	Could not complete propagation of "2003-corolla-crash-court/2019-04-04-Police-Footage/.19012730_Spofford_redacted.mp4.~17a3fb8" by OCC::PropagateUploadFileNG(0x55933d58f2a0) with status 3 and error: "Local file changed during syncing. It will be resumed."
[OCC::ActivityWidget::slotItemCompleted 	Item  "2003-corolla-crash-court/2019-04-04-Police-Footage/.19012730_Spofford_redacted.mp4.~17a3fb8"  retrieved resulted in  "Local file changed during syncing. It will be resumed."
[OCC::ActivityWidget::slotItemCompleted 	Item  "2003-corolla-crash-court/2019-04-04-Police-Footage/.19012730_Spofford_redacted.mp4.~17a3fb8"  retrieved resulted in error  "Local file changed during syncing. It will be resumed."
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Local file changed during syncing. It will be resumed."
[OCC::PropagatorCompositeJob::slotSubJobFinished 	ASSERT: "i >= 0" in file /build/nextcloud-client-ajeKCj/nextcloud-client-2.5.2/src/libsync/owncloudpropagator.cpp, line 834

**Comment by LEDfan** [comment]
I'm also experiencing very regular segfaults. I'm use the nextcloud-client package from the [opensuse network repo](https://build.opensuse.org/package/show/network/nextcloud-client) on openSUSE Leap 15.0. I installed the debug packages () and ran the client in gdb to catch the stacktrace.

<details>

```
Thread 1 "nextcloud" received signal SIGSEGV, Segmentation fault.
QVector<OCC::PropagatorJob*>::indexOf (from=0, t=
    <synthetic pointer>: 0x55555613eef0, this=0x55555673e6c8)
    at /usr/include/qt5/QtCore/qvector.h:850
850	            if (*n == t)
(gdb) bt
#0  0x00007ffff73f72b8 in QVector<OCC::PropagatorJob*>::indexOf(OCC::PropagatorJob* const&, int) const
    (from=0, t=<synthetic pointer>: 0x55555613eef0, this=0x55555673e6c8)
    at /usr/include/qt5/QtCore/qvector.h:850
#1  0x00007ffff73f72b8 in OCC::PropagatorCompositeJob::slotSubJobFinished(OCC::SyncFileItem::Status) (this=0x55555673e698, status=OCC::SyncFileItem::SoftError)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:833
#2  0x00007fffebea615c in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7fffffffc430, r=0x55555673e698, this=0x555555f1d800)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:101
#3  0x00007fffebea615c in QMetaObject::activate(QObject*, int, int, void**)
    (sender=sender@entry=0x55555613eef0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffc430)
    at kernel/qobject.cpp:3749
#4  0x00007fffebea6767 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**)
    (sender=sender@entry=0x55555613eef0, m=m@entry=0x7ffff76bf0a0 <OCC::PropagatorJob::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffc430) at kernel/qobject.cpp:3628
#5  0x00007ffff74712de in OCC::PropagatorJob::finished(OCC::SyncFileItem::Status) (this=this@entry=0x55555613eef0, _t1=<optimized out>)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/build/src/libsync--Type <RET> for more, q to quit, c to continue without paging--
/nextcloudsync_autogen/EWIEGA46WW/moc_owncloudpropagator.cpp:160
#6  0x00007ffff73f44a5 in OCC::PropagateItemJob::done(OCC::SyncFileItem::Status, QString const&)
    (this=0x55555613eef0, statusArg=<optimized out>, errorString=...)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:281
#7  0x00007ffff7410657 in OCC::PropagateUploadFileCommon::slotStartUpload(QByteArray const&, QByteArray const&)
    (this=0x55555613eef0, transmissionChecksumType=..., transmissionChecksum=...)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/propagateupload.cpp:362
#8  0x00007fffebea615c in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7fffffffc730, r=0x55555613eef0, this=0x555556b29ad0)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:101
#9  0x00007fffebea615c in QMetaObject::activate(QObject*, int, int, void**)
    (sender=sender@entry=0x7fff700027c0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffc730)
    at kernel/qobject.cpp:3749
#10 0x00007fffebea6767 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**)
    (sender=sender@entry=0x7fff700027c0, m=m@entry=0x7ffff73409c0 <OCC::ComputeChecksum::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=--Type <RET> for more, q to quit, c to continue without paging--
argv@entry=0x7fffffffc730) at kernel/qobject.cpp:3628
#11 0x00007ffff712e5c7 in OCC::ComputeChecksum::done(QByteArray const&, QByteArray const&) (this=this@entry=0x7fff700027c0, _t1=..., _t2=...)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/build/src/csync/ocsync_autogen/AAGGKE4ILT/moc_checksums.cpp:137
#12 0x00007ffff70fbb94 in OCC::ComputeChecksum::slotCalculationDone()
    (this=0x7fff700027c0)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/common/checksums.cpp:213
#13 0x00007fffebea615c in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7fffffffc840, r=0x7fff700027c0, this=0x555556b29c00)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:101
#14 0x00007fffebea615c in QMetaObject::activate(QObject*, int, int, void**)
    (sender=0x7fff700027d8, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3749
#15 0x00007fffebca22f3 in QFutureWatcherBase::event(QEvent*)
    (this=<optimized out>, event=0x7fff68003b40)
    at thread/qfuturewatcher.cpp:335
#16 0x00007fffecc08e8c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    (this=this@entry=
    0x555555a44c00, receiver=receiver@entry=0x7fff700027d8, e=e@entry=0x7fff68003b40) at kernel/qapplication.cpp:3723
#17 0x00007fffecc10244 in QApplication::notify(QObject*, QEvent*)
--Type <RET> for more, q to quit, c to continue without paging--
    (this=0x7fffffffce20, receiver=0x7fff700027d8, e=0x7fff68003b40)
    at kernel/qapplication.cpp:3482
#18 0x00007fffebe78a88 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    (receiver=0x7fff700027d8, event=event@entry=0x7fff68003b40)
    at kernel/qcoreapplication.cpp:1016
#19 0x00007fffebe7b075 in QCoreApplication::sendEvent(QObject*, QEvent*)
    (event=0x7fff68003b40, receiver=<optimized out>)
    at kernel/qcoreapplication.h:233
#20 0x00007fffebe7b075 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)
    (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x555555a7de00) at kernel/qcoreapplication.cpp:1676
#21 0x00007fffebe7b5f8 in QCoreApplication::sendPostedEvents(QObject*, int)
    (receiver=receiver@entry=0x0, event_type=event_type@entry=0)
    at kernel/qcoreapplication.cpp:1530
#22 0x00007fffebecf583 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x555555ba7820) at kernel/qeventdispatcher_glib.cpp:276
#23 0x00007fffe01a6e07 in g_main_dispatch (context=0x7fffcc004fc0)
    at gmain.c:3142
#24 0x00007fffe01a6e07 in g_main_context_dispatch
    (context=context@entry=0x7fffcc004fc0) at gmain.c:3795
#25 0x00007fffe01a71b0 in g_main_context_iterate
    (context=context@entry=0x7fffcc004fc0, block=block@entry=1, dispatch=dispatc--Type <RET> for more, q to quit, c to continue without paging--
h@entry=1, self=<optimized out>) at gmain.c:3868
#26 0x00007fffe01a723c in g_main_context_iteration
    (context=0x7fffcc004fc0, may_block=may_block@entry=1) at gmain.c:3929
#27 0x00007fffebecebff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x555555bab320, flags=...)
    at kernel/qeventdispatcher_glib.cpp:423
#28 0x00007fffebe7709a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffcd70, flags=..., flags@entry=...)
    at kernel/qeventloop.cpp:212
#29 0x00007fffebe7f9e4 in QCoreApplication::exec() ()
    at kernel/qcoreapplication.cpp:1289
#30 0x0000555555602fa8 in main(int, char**)
    (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/gui/main.cpp:167
```
</details>

and

<details>

```
#0  0x00007ffff73f74f2 in OCC::PropagatorCompositeJob::scheduleSelfOrChild() (this=0x555555ee86c8)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:781
#1  0x00007ffff73f7c7b in OCC::PropagateDirectory::scheduleSelfOrChild() (this=<optimized out>)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:921
#2  0x00007ffff73f7605 in OCC::PropagatorCompositeJob::possiblyRunNextJob(OCC::PropagatorJob*) (next=0x555555ee8690, this=0x5555561fe908)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.h:274
#3  0x00007ffff73f7605 in OCC::PropagatorCompositeJob::scheduleSelfOrChild() (this=0x5555561fe908)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:783
#4  0x00007ffff73f7c7b in OCC::PropagateDirectory::scheduleSelfOrChild() (this=<optimized out>)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:921
#5  0x00007ffff73f7605 in OCC::PropagatorCompositeJob::possiblyRunNextJob(OCC::PropagatorJob*) (next=0x5555561fe8d0, this=0x555555fae028)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.h:274
#6  0x00007ffff73f7605 in OCC::PropagatorCompositeJob::scheduleSelfOrChild() (this=0x555555fae028)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:783
#7  0x00007ffff73f7c7b in OCC::PropagateDirectory::scheduleSelfOrChild() (this=<optimized out>)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:921
#8  0x00007ffff73f7605 in OCC::PropagatorCompositeJob::possiblyRunNextJob(OCC::PropagatorJob*) (next=0x555555fadff0, this=0x5555560945a8)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.h:274
#9  0x00007ffff73f7605 in OCC::PropagatorCompositeJob::scheduleSelfOrChild() (this=0x5555560945a8)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:783
#10 0x00007ffff73f7c7b in OCC::PropagateDirectory::scheduleSelfOrChild() (this=<optimized out>)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:921
#11 0x00007ffff73f7605 in OCC::PropagatorCompositeJob::possiblyRunNextJob(OCC::PropagatorJob*) (next=0x555556094570, this=0x555555f5ab08)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.h:274
#12 0x00007ffff73f7605 in OCC::PropagatorCompositeJob::scheduleSelfOrChild() (this=0x555555f5ab08)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:783
#13 0x00007ffff73f7c7b in OCC::PropagateDirectory::scheduleSelfOrChild() (this=<optimized out>)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:921
#14 0x00007ffff73f3c33 in OCC::OwncloudPropagator::scheduleNextJobImpl() (this=0x5555563049b0)
    at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/libsync/owncloudpropagator.cpp:605
#15 0x00007fffebeb24c7 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffc878, r=<optimized out>, this=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:101
#16 0x00007fffebeb24c7 in QSingleShotTimer::timerEvent(QTimerEvent*) (this=0x5555566f5db0) at kernel/qtimer.cpp:318
#17 0x00007fffebea69fb in QObject::event(QEvent*) (this=0x5555566f5db0, e=<optimized out>) at kernel/qobject.cpp:1268
#18 0x00007fffecc08e8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x555555a44c00, receiver=receiver@entry=0x5555566f5db0, e=e@entry=0x7fffffffcb30)
    at kernel/qapplication.cpp:3723
#19 0x00007fffecc10244 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffce20, receiver=0x5555566f5db0, e=0x7fffffffcb30) at kernel/qapplication.cpp:3482
#20 0x00007fffebe78a88 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x5555566f5db0, event=event@entry=0x7fffffffcb30) at kernel/qcoreapplication.cpp:1016
#21 0x00007fffebece1ae in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7fffffffcb30, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:233
#22 0x00007fffebece1ae in QTimerInfoList::activateTimers() (this=0x555555baa160) at kernel/qtimerinfo_unix.cpp:643
#23 0x00007fffebece8c1 in timerSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:182
#24 0x00007fffe01a6e07 in g_main_dispatch (context=0x7fffcc004fc0) at gmain.c:3142
#25 0x00007fffe01a6e07 in g_main_context_dispatch (context=context@entry=0x7fffcc004fc0) at gmain.c:3795
#26 0x00007fffe01a71b0 in g_main_context_iterate (context=context@entry=0x7fffcc004fc0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3868
#27 0x00007fffe01a723c in g_main_context_iteration (context=0x7fffcc004fc0, may_block=may_block@entry=1) at gmain.c:3929
#28 0x00007fffebecebff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x555555badd00, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#29 0x00007fffebe7709a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffcd70, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#30 0x00007fffebe7f9e4 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1289
#31 0x0000555555602fa8 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/nextcloud-client-2.5.2-lp150.51.3.x86_64/src/gui/main.cpp:167
```
</details>

Not sure why I'm seeing this now, since the package on OBS hasn't been updated for 2months.

**Comment by geez0x1** [comment]
I'm also seeing this issue with 2.5.1git from the Debian stable repositories:

```
kernel: [0000.000] traps: nextcloud[4685] general protection ip:7fec6180f070 sp:7fff3335cc10 error:0 in libnextcloudsync.so.2.5.1[7fec617ac000+e3000]
```

**Comment by DominiqueFuchs** [comment]
Please continue posting informations about segfault occurences in #241 , thanks!
