### ISSUE TITLE
Segmentation fault in QMutex::lock()

### ISSUE THREAD

**Issue by epsilontheta** [nextcloud/desktop#1684]
### Expected behaviour
Client should not crash when opening the settings.

### Actual behaviour
It crashes.

### Steps to reproduce
0. // Not 100% reproducible
1. Start nextcloud client
2. Pause sync through menu
3. Send computer to sleep
4. Wake up 
5. Resume sync
5. Open settings menu

### Client configuration
Client version: 2.6.1

Operating system: Arch Linux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.13.2

Client package (From Nextcloud or distro) (Linux only): 2.6.1-3

Installation path of client: /usr/bin/nextcloud

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile:
```
Dez 18 01:34:03 tarvos nextcloud.desktop[75571]: [75571:75581:1218/013403.810219:ERROR:browser_gpu_channel_host_factory.cc(138)] Failed to launch GPU process.
Dez 18 01:34:03 tarvos nextcloud.desktop[75571]: Opening in existing browser session.
Dez 18 01:34:07 tarvos audit[33224]: ANOM_ABEND auid=1001 uid=1001 gid=1001 ses=3 pid=33224 comm="nextcloud" exe="/usr/bin/nextcloud" sig=11 res=1
Dez 18 01:34:07 tarvos kernel: traps: nextcloud[33224] general protection fault ip:7f14e39139a7 sp:7ffec131d408 error:0 in libQt5Core.so.5.13.2[7f14e38d7000+2ea000]
Dez 18 01:34:07 tarvos kernel: audit: type=1701 audit(1576629247.438:266): auid=1001 uid=1001 gid=1001 ses=3 pid=33224 comm="nextcloud" exe="/usr/bin/nextcloud" sig=11 res=1
Dez 18 01:34:07 tarvos systemd[1]: Started Process Core Dump (PID 75629/UID 0).
Dez 18 01:34:07 tarvos audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-75629-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dez 18 01:34:07 tarvos kernel: audit: type=1130 audit(1576629247.484:267): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-75629-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=suc>

Core was generated by `nextcloud'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f14e39139a7 in QMutex::lock() () from /usr/lib/libQt5Core.so.5
[Current thread is 1 (Thread 0x7f14d9a0eb00 (LWP 33224))]
(gdb) bt
#0  0x00007f14e39139a7 in QMutex::lock() () at /usr/lib/libQt5Core.so.5
#1  0x00007f14e3ae502c in QCoreApplication::postEvent(QObject*, QEvent*, int) () at /usr/lib/libQt5Core.so.5
#2  0x00007f14ec82c5de in OCC::AbstractNetworkJob::slotFinished() () at /usr/lib/libnextcloudsync.so.0
#3  0x00007f14e3b0dc20 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#4  0x00007f14e4b32d2f in  () at /usr/lib/libQt5Network.so.5
#5  0x00007f14e3b0e4fa in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#6  0x00007f14e449b4e5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007f14e44a4e11 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007f14e3ae1d12 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#9  0x00007f14e3ae4a89 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#10 0x00007f14e3b3a514 in  () at /usr/lib/libQt5Core.so.5
#11 0x00007f14e2dfe39e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#12 0x00007f14e2e001b1 in  () at /usr/lib/libglib-2.0.so.0
#13 0x00007f14e2e001f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#14 0x00007f14e3b39b13 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#15 0x00007f14e3ae083c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#16 0x00007f14e3ae8676 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#17 0x000055a4791d1953 in main ()
(gdb) 


```

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by mhoeher** [comment]
I can confirm this issue (with the exact same backtrace). I am currently using version 2.6.2 of the client on Fedora 31 (installed from the Fedora repository). The crash occurs infrequently but does not seem to be related to opening the settings but also seems to happen from time to time when the app just runs in the background.

This is quite bad as this might lead to the sync client not running at all without the user noticing it and consequentially not getting any updates anymore.

What I noticed:

The crash seems to happen often after some network sync issues. In this case, the tray icon shows a little red overlay to indicate problems. When clicking the icon (which should bring up the app) it immediately crashes.
