### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by eknoes** [nextcloud/desktop#441]
This may be related to #241 and #219.

I use Arch Linux with the latest nextcloud desktop client release and got a segmentation fault. I downloaded the current git state to get a stacktrace.

```
Thread 1 "nextcloud" received signal SIGSEGV, Segmentation fault.
0x00007fffbd858342 in gdk_display_open () from /usr/lib/libgdk-x11-2.0.so.0
(gdb) backtrace
#0  0x00007fffbd858342 in gdk_display_open () at /usr/lib/libgdk-x11-2.0.so.0
#1  0x00007fffbd827052 in gdk_display_open_default_libgtk_only () at /usr/lib/libgdk-x11-2.0.so.0
#2  0x00007fffbdbeac83 in gtk_init () at /usr/lib/libgtk-x11-2.0.so.0
#3  0x00007fffbe120dfb in  () at /usr/lib/qt/plugins/styles/libqgtk2style.so
#4  0x00007fffbe122560 in  () at /usr/lib/qt/plugins/styles/libqgtk2style.so
#5  0x00007fffe9fdc62d in QStyleFactory::create(QString const&) () at /usr/lib/libQt5Widgets.so.5
#6  0x00007fffea00363d in QProxyStyle::QProxyStyle(QString const&) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007fffc40d022c in Qt5CTProxyStyle::Qt5CTProxyStyle(QString const&) () at /usr/lib/qt/plugins/styles/libqt5ct-style.so
#8  0x00007fffc40cfec1 in Qt5CTStylePlugin::create(QString const&) () at /usr/lib/qt/plugins/styles/libqt5ct-style.so
#9  0x00007fffe9fdc62d in QStyleFactory::create(QString const&) () at /usr/lib/libQt5Widgets.so.5
#10 0x00007fffe9f7045c in QApplication::style() () at /usr/lib/libQt5Widgets.so.5
#11 0x00007fffe9f706e6 in QApplicationPrivate::initialize() () at /usr/lib/libQt5Widgets.so.5
#12 0x00007fffe9f7074b in QApplicationPrivate::init() () at /usr/lib/libQt5Widgets.so.5
#13 0x000055555585382b in SharedTools::QtSingleApplication::QtSingleApplication(QString const&, int&, char**) (this=0x7fffffffddf0, appId=..., argc=@0x7fffffffdd8c: 1, argv=0x7fffffffdfc8)
    at /home/XXXX/Projekte/desktop/src/3rdparty/qtsingleapplication/qtsingleapplication.cpp:56
#14 0x00005555556ed49b in OCC::Application::Application(int&, char**) (this=0x7fffffffddf0, argc=@0x7fffffffdd8c: 1, argv=0x7fffffffdfc8) at /home/XXXX/Projekte/desktop/src/gui/application.cpp:108
#15 0x00005555556c7b82 in main(int, char**) (argc=1, argv=0x7fffffffdfc8) at /home/XXXX/Projekte/desktop/src/gui/main.cpp:74
```

I have Linux Kernel 4.17.2, nextcloudcmd --version produces the following output:
```
Nextcloud version 2.5.0git
Git revision 10f08159bdcc3bb1afa3fc49eaab9364ea50ae53
Using Qt 5.11.0, built against Qt 5.11.0
Using 'OpenSSL 1.1.0h  27 Mar 2018'
```

The error arises when starting `/bin/nextcloud`

**Comment by camilasan** [comment]
Hi, this needs further debugging but in the meantime, could you try the latest AppImage?
https://download.nextcloud.com/desktop/daily/Linux/

**Comment by eknoes** [comment]
Hi, this one works fine!

**Comment by DominiqueFuchs** [comment]
Further possible segfault appearences in: #241
