### ISSUE TITLE
[Bug]: Crash when adding a new remote folder

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/desktop#4855]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Crash when adding a new remote folder and syncing

```
#0  0x00007f4801d3c201 in g_type_check_instance_is_fundamentally_a () at /lib64/libgobject-2.0.so.0
#1  0x00007f4801d25ab9 in g_object_unref () at /lib64/libgobject-2.0.so.0
#2  0x00005647c63ea8f5 in CloudProviderWrapper::getActionGroup() (this=0x5647c8de6160) at /home/cschwan/nextcloud/client/src/gui/cloudproviders/cloudproviderwrapper.cpp:340
#3  0x00005647c63e84ab in CloudProviderWrapper::CloudProviderWrapper(QObject*, OCC::Folder*, int, _CloudProvidersProviderExporter*)
    (this=0x5647c8de6160, parent=0x5647c8463a70, folder=0x5647c8728400, folderId=1, cloudprovider=0x7f475800d8e0) at /home/cschwan/nextcloud/client/src/gui/cloudproviders/cloudproviderwrapper.cpp:50
#4  0x00005647c63e74b9 in CloudProviderManager::slotFolderListChanged(QMap<QString, OCC::Folder*> const&) (this=0x5647c8463a70, folderMap=...) at /home/cschwan/nextcloud/client/src/gui/cloudproviders/cloudprovidermanager.cpp:73
#5  0x00005647c619a316 in CloudProviderManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x5647c8463a70, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffcb639580)
    at /home/cschwan/nextcloud/client/build/src/gui/nextcloudCore_autogen/D4IE7O3YUE/moc_cloudprovidermanager.cpp:75
#6  0x00007f480187f820 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt5Core.so.5
#7  0x00005647c619ea5e in OCC::FolderMan::folderListChanged(QMap<QString, OCC::Folder*> const&) (this=0x5647c80afd40, _t1=...) at /home/cschwan/nextcloud/client/build/src/gui/nextcloudCore_autogen/EWIEGA46WW/moc_folderman.cpp:328
#8  0x00005647c6224da9 in OCC::FolderMan::addFolder(OCC::AccountState*, OCC::FolderDefinition const&) (this=0x5647c80afd40, accountState=0x5647c8417140, folderDefinition=...)
    at /home/cschwan/nextcloud/client/src/gui/folderman.cpp:1117
#9  0x00005647c61d08d2 in OCC::AccountSettings::slotFolderWizardAccepted() (this=0x5647c8cb15c0) at /home/cschwan/nextcloud/client/src/gui/accountsettings.cpp:720
#10 0x00005647c61e3c47 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (OCC::AccountSettings::*)()>::call(void (OCC::AccountSettings::*)(), OCC::AccountSettings*, void**)
    (f=(void (OCC::AccountSettings::*)(OCC::AccountSettings * const)) 0x5647c61d02e8 <OCC::AccountSettings::slotFolderWizardAccepted()>, o=0x5647c8cb15c0, arg=0x7fffcb639910) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:152
#11 0x00005647c61e2df8 in QtPrivate::FunctionPointer<void (OCC::AccountSettings::*)()>::call<QtPrivate::List<>, void>(void (OCC::AccountSettings::*)(), OCC::AccountSettings*, void**)
    (f=(void (OCC::AccountSettings::*)(OCC::AccountSettings * const)) 0x5647c61d02e8 <OCC::AccountSettings::slotFolderWizardAccepted()>, o=0x5647c8cb15c0, arg=0x7fffcb639910) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:185
#12 0x00005647c61e17af in QtPrivate::QSlotObject<void (OCC::AccountSettings::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x5647c8871d30, r=0x5647c8cb15c0, a=0x7fffcb639910, ret=0x0) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:418
#13 0x00007f480187f7d9 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt5Core.so.5
#14 0x00007f4802b54798 in QDialogPrivate::finalize(int, int) () at /lib64/libQt5Widgets.so.5
#15 0x00007f480187f820 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt5Core.so.5
#16 0x00007f4802a3a716 in QAbstractButton::clicked(bool) () at /lib64/libQt5Widgets.so.5
#17 0x00007f4802a3a99e in QAbstractButtonPrivate::emitClicked() () at /lib64/libQt5Widgets.so.5
#18 0x00007f4802a3c5c4 in QAbstractButtonPrivate::click() () at /lib64/libQt5Widgets.so.5
#19 0x00007f4802a3c7e7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib64/libQt5Widgets.so.5
#20 0x00007f4802987ffe in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#21 0x00007f4802945443 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#22 0x00007f480294d074 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#23 0x00007f480184bbe8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#24 0x00007f480294bb57 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib64/libQt5Widgets.so.5
#25 0x00007f48029a15e0 in QWidgetWindow::handleMouseEvent(QMouseEvent*) () at /lib64/libQt5Widgets.so.5
#26 0x00007f48029a4875 in QWidgetWindow::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#27 0x00007f4802945443 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#28 0x00007f480184bbe8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#29 0x00007f48022c1c28 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib64/libQt5Gui.so.5
#30 0x00007f48022a1d7c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Gui.so.5
#31 0x00007f47e90f46c4 in userEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5WaylandClient.so.5
#32 0x00007f4801c1f0af in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#33 0x00007f4801c74308 in g_main_context_iterate.constprop () at /lib64/libglib-2.0.so.0
#34 0x00007f4801c1c8a3 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#35 0x00007f480189cffe in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#36 0x00007f480184a5f2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#37 0x00007f4801852b34 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#38 0x00005647c618cf5f in main(int, char**) (argc=1, argv=0x7fffcb63a938) at /home/cschwan/nextcloud/client/src/gui/main.cpp:225
```

### Steps to reproduce

Can't really reproduce it or at least not easily, hopefully the backtrace is enough

### Expected behavior

Not a crash

### Which files are affected by this bug

no file, didn't sync yet

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 35

### Package

Compiled it myself

### Nextcloud Server version

git master

### Nextcloud Desktop Client version

master hash: 577ee4a7172aaa63f7536eb39b5d36c590d84760

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
nothing interesting there
```

**Comment by CarlSchwan** [comment]
Looking a bit at the code, this is wrapping a gnome lib to do dbus stuff. I'm not sure how this works with the event loops but that seems a bit messy and error prone.

Would it not be easier to ask Qt to generate the C++ for the dbus API in https://gitlab.gnome.org/World/libcloudproviders/-/blob/master/data/cloud-providers-dbus.xml and directly use it? It would b simpler and remove a dep

**Comment by juliushaertl** [comment]
> Looking a bit at the code, this is wrapping a gnome lib to do dbus stuff. I'm not sure how this works with the event loops but that seems a bit messy and error prone.

> Would it not be easier to ask Qt to generate the C++ for the dbus API in [gitlab.gnome.org/World/libcloudproviders/-/blob/master/data/cloud-providers-dbus.xml](https://gitlab.gnome.org/World/libcloudproviders/-/blob/master/data/cloud-providers-dbus.xml) and directly use it? It would b simpler and remove a dep

Sounds like a sane idea I'd say.

**Comment by nilsding** [comment]
from what I can tell this was fixed with #5845 -- if the crash still occurs in a recent version please re-open this issue
