### ISSUE TITLE
Nextcloud desktop gui crashes in XFCE over x2go

### ISSUE THREAD

**Issue by pielonet** [nextcloud/desktop#587]
Hi,
Nextcloud desktop works well under XFCE over X2go. Syncing is ok and I get a nice green icon in notification bar.
The GUI used to work perfectly until recently (a few days or weeks). Now I can't launch the GUI and modify parameters : Nextcloud desktop GUI crashes immediately.

I get the following log : 

```
08-27 10:35:45:796 1290 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
08-27 10:35:45:853 1290 unknown: The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 2 (Aucun fichier ou dossier de ce type) on X server ":50.0"
      after 391 requests (391 known processed) with 0 events remaining.
```
Any idea what is going wrong ?

Thierry

**Comment by camilasan** [comment]
Hi! Could you tell us exactly which daily build was it? Thanks!

**Comment by pielonet** [comment]
Hi, how do I get the build number ?

**Comment by camilasan** [comment]
It is displayed in the General settings.

**Comment by pielonet** [comment]
Unfortunately the application crashes before I can open the parameters' window...

**Comment by camilasan** [comment]
Don't you have the the exe that you downloaded? The date it is in the file name.

**Comment by pielonet** [comment]
I do not have an exe. I am under linux. I install nextcloud-client from this ubuntu ppa : https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client
So the exact version is : 2.3.3-20180415.190957~xenial1

**Comment by avmediadesign** [comment]
Same issue here...

**Comment by pielonet** [comment]
up !
Still an issue !

**Comment by cbienmueller** [comment]
Here too, xubuntu 18.04, all updates installed, nextcloud-client from ppa
1. When accessed via x2go, nextcloud on the commandline throws the following error
```
$ nextcloud
XIO:  fatal IO error 2 (Datei oder Verzeichnis nicht gefunden) on X server ":50.0"
      after 428 requests (428 known processed) with 0 events remaining.
```
2. Directly accessed (via the KVM-Console (VNC)) it can be configured, syncs etc.

**Comment by avmediadesign** [comment]
Could somebody at Nextcloud please have a look at this (serious) issue ?
There is no way to get the client running on Ubuntu 16.04 via X2go (latest version).
I have checked with 2.3.3-20180415.190957~xenial1 and also with the latest 2.5 AppImage (and also with the Owncloud client).
Always the same error :
```
XIO:  fatal IO error 2 (Aucun fichier ou dossier de ce type) on X server ":50.0"
      after 391 requests (391 known processed) with 0 events remaining.
```

**Comment by stony245** [comment]
Same issue here. Cannot use it in any way.
Environment: 
Ubuntu Mate 18.04 in an LXC container via X2Go
PPA from ppa:nextcloud-devs/client

```
user@remote:~$ nextcloud
Gdk-Message: 15:24:51.188: nextcloud: Fatal IO error 2 (Datei oder Verzeichnis nicht gefunden) on X server :50.

```
Using current Appimages I get
```
user@remote:~/Downloads$ ./Nextcloud-2.5.0.20181018-daily-x86_64.AppImage
[8245:8312:1018/182843.504453:ERROR:gl_surface_glx_qt.cpp(143)] GLX 1.3 or later is required.
[8245:8312:1018/182843.504478:ERROR:gl_surface_egl_qt.cpp(77)] GLContextHelper::getEGLDisplay() failed.
XIO:  fatal IO error 0 (Erfolg) on X server ":50"
      after 440 requests (440 known processed) with 0 events remaining.

```

**Comment by pielonet** [comment]
Hi, anybody alive at Netxcloud team to help solve this (blocking) issue ?

**Comment by avmediadesign** [comment]
Hi,
Enabling BIG-REQUESTS in /etc/x2go/x2goagent.options + server restart solves the issue for me.
Just comment out the line "X2GO_NXAGENT_DEFAULT_OPTIONS+=" -extension BIG_REQUESTS"
Hope this helps.

**Comment by cbienmueller** [comment]
Hi, 
I don't know of any side effects, but the solution from avmediadesign works for me too (Xubuntu 18.04)! Thanks a lot!

**Comment by stony245** [comment]
This solved my Problem also but only with nextcloud clients upto 2.3.3.
2.5.0 threw

> WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!
[3176:3238:1105/132817.136618:ERROR:gl_surface_qt.cpp(312)] Requested OpenGL implementation is not supported. Implementation: 0
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7fa1465946af <unknown>
#1 0x7fa144fc38c5 <unknown>
#2 0x7fa146594bbe <unknown>
#3 0x7fa1427aaf20 <unknown>
#4 0x7fa145025ca2 <unknown>
#5 0x7fa145010928 <unknown>
#6 0x7fa14708683d <unknown>
#7 0x7fa1490490a7 <unknown>
#8 0x7fa14904c070 <unknown>
#9 0x7fa149047596 <unknown>
#10 0x7fa14904525f <unknown>
#11 0x7fa1490467a2 <unknown>
#12 0x7fa14904833d <unknown>
#13 0x7fa146594db9 <unknown>
#14 0x7fa1465b6250 <unknown>
#15 0x7fa1465b6cad <unknown>
#16 0x7fa1465b6f97 <unknown>
#17 0x7fa1465b2b29 <unknown>
#18 0x7fa1465d92df <unknown>
#19 0x7fa1465fca0f <unknown>
#20 0x7fa1465f8070 [3176:3229:1105/132817.145804:ERROR:cert_verify_proc_nss.cc(944)] CERT_PKIXVerifyCert for 10.10.10.13 failed err=-8172
<unknown>

**Comment by arno01** [comment]
Just occurred to me:

```
[Mon Sep 30 07:19:44 2019] nextcloud[1212]: segfault at 20 ip 0000561589648f49 sp 00007ffc4b06fc20 error 4 in nextcloud[56158952b000+2da000]

DistroRelease: Ubuntu 18.04
ii  nextcloud-client                            2.6.0-20190927.150124~bionic1                amd64        Nextcloud desktop sync client
ii  xwayland                                    2:1.19.6-1ubuntu4.3                          amd64        Xwayland X server

ProcStatus:
 Name:  nextcloud
 Umask: 0002
 State: S (sleeping)
 Tgid:  1212
 Ngid:  0
 Pid:   1212
 PPid:  1
 TracerPid:     0
 Uid:   1000    1000    1000    1000
 Gid:   1000    1000    1000    1000
 FDSize:        64
 Groups:        4 24 27 30 46 116 126 129 135 998 999 1000 
 NStgid:        1212
 NSpid: 1212
 NSpgid:        1211
 NSsid: 1211
 VmPeak:         1428888 kB
 VmSize:         1380184 kB
 VmLck:        0 kB
 VmPin:        0 kB
 VmHWM:    91596 kB
 VmRSS:    88940 kB
 RssAnon:          25908 kB
 RssFile:          62832 kB
 RssShmem:           200 kB
 VmData:          115292 kB
 VmStk:      132 kB
 VmExe:     2920 kB
 VmLib:   307048 kB
 VmPTE:     1344 kB
 VmSwap:               0 kB
 HugetlbPages:         0 kB
 CoreDumping:   1
 Threads:       9
 SigQ:  0/30856
 SigPnd:        0000000000000000
 ShdPnd:        0000000000000000
 SigBlk:        0000000000000000
 SigIgn:        0000000000001000
 SigCgt:        0000000180010000
 CapInh:        0000000000000000
 CapPrm:        0000000000000000
 CapEff:        0000000000000000
 CapBnd:        0000003fffffffff
 CapAmb:        0000000000000000
 NoNewPrivs:    0
 Seccomp:       0
 Speculation_Store_Bypass:      thread vulnerable
 Cpus_allowed:  ff
 Cpus_allowed_list:     0-7
 Mems_allowed:  00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
 Mems_allowed_list:     0
 voluntary_ctxt_switches:       226
 nonvoluntary_ctxt_switches:    194
Signal: 11
Uname: Linux 4.15.0-64-generic x86_64

Disassembly:
 => 0x561589648f49 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+25>:       mov    0x20(%rdi),%rax
    0x561589648f4d <_ZN3OCC11ownCloudGui16slotShowSettingsEv+29>:       test   %rax,%rax
    0x561589648f50 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+32>:       je     0x561589648fa0 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+112>
    0x561589648f52 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+34>:       mov    0x4(%rax),%edx
    0x561589648f55 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+37>:       test   %edx,%edx
    0x561589648f57 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+39>:       je     0x561589648fa0 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+112>
    0x561589648f59 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+41>:       cmpq   $0x0,0x28(%rdi)
    0x561589648f5e <_ZN3OCC11ownCloudGui16slotShowSettingsEv+46>:       je     0x561589648fa0 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+112>
    0x561589648f60 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+48>:       test   %rax,%rax
    0x561589648f63 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+51>:       je     0x561589649054 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+292>
    0x561589648f69 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+57>:       mov    0x4(%rax),%eax
    0x561589648f6c <_ZN3OCC11ownCloudGui16slotShowSettingsEv+60>:       test   %eax,%eax
    0x561589648f6e <_ZN3OCC11ownCloudGui16slotShowSettingsEv+62>:       je     0x561589649054 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+292>
    0x561589648f74 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+68>:       mov    0x28(%rbx),%rdi
    0x561589648f78 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+72>:       callq  0x561589648ef0 <_ZN3OCC11ownCloudGui11raiseDialogEP7QWidget>
    0x561589648f7d <_ZN3OCC11ownCloudGui16slotShowSettingsEv+77>:       mov    0x28(%rsp),%rax
InstallationDate: Installed on 2018-07-24 (438 days ago)
InstallationMedia: Ubuntu 18.04 LTS "Bionic Beaver" - Release amd64 (20180426)

SegvAnalysis:
 Segfault happened at: 0x561589648f49 <_ZN3OCC11ownCloudGui16slotShowSettingsEv+25>:    mov    0x20(%rdi),%rax
 PC (0x561589648f49) ok
 source "0x20(%rdi)" (0x00000020) not located in a known VMA region (needed readable region)!
 destination "%rax" ok
SegvReason: reading NULL VMA
SourcePackage: nextcloud-client
Stacktrace:
 #0  0x0000561589648f49 in OCC::ownCloudGui::slotShowSettings() ()
 No symbol table info available.
 #1  0x00005615895d811e in main ()
 No symbol table info available.
StacktraceTop:
 OCC::ownCloudGui::slotShowSettings() ()
 main ()
Tags: third-party-packages wayland-session bionic
ThreadStacktrace:
 .
 Thread 9 (Thread 0x7f54637b1700 (LWP 1215)):
 #0  0x00007f5489728bf9 in __GI___poll (fds=0x56158a86a830, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimised out>
 #1  0x00007f548719a5c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007f548719a6dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007f54637b936d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
 No symbol table info available.
 #4  0x00007f54871c2195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #5  0x00007f54893fc6db in start_thread (arg=0x7f54637b1700) at pthread_create.c:463
         pd = 0x7f54637b1700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140000422991616, -922710570288367723, 140000422988672, 0, 94650518351088, 140721567226704, 979842251472942997, 979759279000172437}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
 #6  0x00007f548973588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 8 (Thread 0x7f546ab33700 (LWP 1214)):
 #0  0x00007f5489728bf9 in __GI___poll (fds=0x7f546ab32928, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimised out>
 #1  0x00007f5485572747 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
 No symbol table info available.
 #2  0x00007f548557436a in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
 No symbol table info available.
 #3  0x00007f546ca315e9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
 No symbol table info available.
 #4  0x00007f548a3f017d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #5  0x00007f54893fc6db in start_thread (arg=0x7f546ab33700) at pthread_create.c:463
         pd = 0x7f546ab33700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140000544110336, -922710570288367723, 140000544107392, 0, 94650518099136, 140721567227744, 979826240908605333, 979759279000172437}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
 #6  0x00007f548973588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 7 (Thread 0x7f54527bc700 (LWP 1220)):
 #0  0x00007f54894029f3 in futex_wait_cancelable (private=<optimised out>, expected=0, futex_word=0x56158a8ad9e8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
         __ret = -512
         oldtype = 0
         err = <optimised out>
         oldtype = <optimised out>
         err = <optimised out>
         __ret = <optimised out>
         resultvar = <optimised out>
         __arg4 = <optimised out>
         __arg3 = <optimised out>
         __arg2 = <optimised out>
         __arg1 = <optimised out>
         _a4 = <optimised out>
         _a3 = <optimised out>
         _a2 = <optimised out>
         _a1 = <optimised out>
 #1  __pthread_cond_wait_common (abstime=0x0, mutex=0x56158a8ad998, cond=0x56158a8ad9c0) at pthread_cond_wait.c:502
         spin = 0
         buffer = {__routine = 0x7f5489402690 <__condvar_cleanup_waiting>, __arg = 0x7f54527bb9c0, __canceltype = 1, __prev = 0x0}
         cbuffer = {wseq = 0, cond = 0x56158a8ad9c0, mutex = 0x56158a8ad998, private = 0}
         rt = <optimised out>
         err = <optimised out>
         g = 0
         flags = <optimised out>
         g1_start = <optimised out>
         signals = <optimised out>
         result = 0
         wseq = <optimised out>
         seq = 0
         private = <optimised out>
         maxspin = <optimised out>
         err = <optimised out>
         result = <optimised out>
         wseq = <optimised out>
         g = <optimised out>
         seq = <optimised out>
         flags = <optimised out>
         private = <optimised out>
         signals = <optimised out>
         g1_start = <optimised out>
         spin = <optimised out>
         buffer = <optimised out>
         cbuffer = <optimised out>
         rt = <optimised out>
         s = <optimised out>
 #2  __pthread_cond_wait (cond=0x56158a8ad9c0, mutex=0x56158a8ad998) at pthread_cond_wait.c:655
 No locals.
 #3  0x00007f545359923b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
 No symbol table info available.
 #4  0x00007f5453598f67 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
 No symbol table info available.
 #5  0x00007f54893fc6db in start_thread (arg=0x7f54527bc700) at pthread_create.c:463
         pd = 0x7f54527bc700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140000137824000, -922710570288367723, 140000137821056, 0, 94650520250320, 140721567223760, 979950009518045077, 979759279000172437}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
 #6  0x00007f548973588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 6 (Thread 0x7f5447fff700 (LWP 1221)):
 #0  0x00007f5489728bf9 in __GI___poll (fds=0x7f5440002990, nfds=1, timeout=10404) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimised out>
 #1  0x00007f548719a5c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007f548719a6dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007f548a62797f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #4  0x00007f548a5cc9fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #5  0x00007f548a3eb23a in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #6  0x00007f548a3f017d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #7  0x00007f54893fc6db in start_thread (arg=0x7f5447fff700) at pthread_create.c:463
         pd = 0x7f5447fff700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139999961937664, -922710570288367723, 139999961934720, 0, 94650522235872, 140721567229232, 979902766488401813, 979759279000172437}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
 #8  0x00007f548973588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 5 (Thread 0x7f5462fb0700 (LWP 1216)):
 #0  0x00007f5489728bf9 in __GI___poll (fds=0x7f545c007a10, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimised out>
 #1  0x00007f548719a5c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007f548719a6dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007f548719a721 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #4  0x00007f54871c2195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #5  0x00007f54893fc6db in start_thread (arg=0x7f5462fb0700) at pthread_create.c:463
         pd = 0x7f5462fb0700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140000414598912, -922710570288367723, 140000414595968, 0, 94650518353536, 140000422987264, 979843350447699861, 979759279000172437}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
 #6  0x00007f548973588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 4 (Thread 0x7f54627af700 (LWP 1217)):
 #0  0x00007f5489728bf9 in __GI___poll (fds=0x7f545c01d020, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimised out>
 #1  0x00007f548719a5c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007f548719a962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007f547f4e20e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
 No symbol table info available.
 #4  0x00007f54871c2195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #5  0x00007f54893fc6db in start_thread (arg=0x7f54627af700) at pthread_create.c:463
         pd = 0x7f54627af700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140000406206208, -922710570288367723, 140000406203264, 0, 94650518353696, 140000422987648, 979844449422456725, 979759279000172437}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
 #6  0x00007f548973588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 3 (Thread 0x7f546e456700 (LWP 1213)):
 #0  0x00007f54894029f3 in futex_wait_cancelable (private=<optimised out>, expected=0, futex_word=0x7f548ed2d110) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
         __ret = -512
         oldtype = 0
         err = <optimised out>
         oldtype = <optimised out>
         err = <optimised out>
         __ret = <optimised out>
         resultvar = <optimised out>
         __arg4 = <optimised out>
         __arg3 = <optimised out>
         __arg2 = <optimised out>
         __arg1 = <optimised out>
         _a4 = <optimised out>
         _a3 = <optimised out>
         _a2 = <optimised out>
         _a1 = <optimised out>
 #1  __pthread_cond_wait_common (abstime=0x0, mutex=0x56158a809580, cond=0x7f548ed2d0e8) at pthread_cond_wait.c:502
         spin = 0
         buffer = {__routine = 0x7f5489402690 <__condvar_cleanup_waiting>, __arg = 0x7f546e4559a0, __canceltype = 0, __prev = 0x0}
         cbuffer = {wseq = 0, cond = 0x7f548ed2d0e8, mutex = 0x56158a809580, private = 0}
         rt = <optimised out>
         err = <optimised out>
         g = 0
         flags = <optimised out>
         g1_start = <optimised out>
         signals = <optimised out>
         result = 0
         wseq = <optimised out>
         seq = 0
         private = <optimised out>
         maxspin = <optimised out>
         err = <optimised out>
         result = <optimised out>
         wseq = <optimised out>
         g = <optimised out>
         seq = <optimised out>
         flags = <optimised out>
         private = <optimised out>
         signals = <optimised out>
         g1_start = <optimised out>
         spin = <optimised out>
         buffer = <optimised out>
         cbuffer = <optimised out>
         rt = <optimised out>
         s = <optimised out>
 #2  __pthread_cond_wait (cond=0x7f548ed2d0e8, mutex=0x56158a809580) at pthread_cond_wait.c:655
 No locals.
 #3  0x00007f548a07286c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 No symbol table info available.
 #4  0x00007f548e06e0a7 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
 No symbol table info available.
 #5  0x00007f548e06e1e9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
 No symbol table info available.
 #6  0x00007f548a07866f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 No symbol table info available.
 #7  0x00007f54893fc6db in start_thread (arg=0x7f546e456700) at pthread_create.c:463
         pd = 0x7f546e456700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140000604022528, -922710570288367723, 140000604019584, 0, 94650517858640, 140721567235248, 979817875922925461, 979759279000172437}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
 #8  0x00007f548973588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 2 (Thread 0x7f5461d92700 (LWP 1218)):
 #0  0x00007f5489728bf9 in __GI___poll (fds=0x7f544c0181b0, nfds=4, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimised out>
 #1  0x00007f548719a5c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007f548719a6dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007f548a62797f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #4  0x00007f548a5cc9fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #5  0x00007f548a3eb23a in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #6  0x00007f54960e5d45 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
 No symbol table info available.
 #7  0x00007f548a3f017d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #8  0x00007f54893fc6db in start_thread (arg=0x7f5461d92700) at pthread_create.c:463
         pd = 0x7f5461d92700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140000395601664, -922710570288367723, 140000395598720, 0, 140001274072416, 140721567227920, 979845258486921109, 979759279000172437}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
 #9  0x00007f548973588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 1 (Thread 0x7f5496515b80 (LWP 1212)):
 #0  0x0000561589648f49 in OCC::ownCloudGui::slotShowSettings() ()
 No symbol table info available.
 #1  0x00005615895d811e in main ()
 No symbol table info available.
Title: nextcloud crashed with SIGSEGV in OCC::ownCloudGui::slotShowSettings()
UnreportableReason: This is not an official Ubuntu package. Please remove any third party package and try again.
UpgradeStatus: No upgrade log present (probably fresh install)
_MarkForUpload: True
```
```

**Comment by idistech** [comment]
Ive still got this as well..
18.04
Nextcloud Client 2.6.0
Mate/X2go

**Comment by veddox** [comment]
This is not (directly) a Nextcloud issue, but a known X2GO problem.

Over X2GO, the client crashes when setting up the login wizard. The reason is that the wizard displays the server login page using the QtWebEngine, which [uses OpenGL for rendering](https://wiki.qt.io/QtWebEngine). Unfortunately, X2GO includes a *really old* OpenGL/GLX implementation - this is the reason why you can only use "low-spec" desktop environments with it. (See the longer explanation [here](https://wiki.x2go.org/doku.php/doc:de-compat).) This is [being worked on](https://github.com/ArcticaProject/nx-libs), but that is a major project that has been ongoing for some years and doesn't seem to be finishing anytime soon.

To circumvent this problem on the Nextcloud side, we'd have to hack up an alternative login screen just for X2GO users, which I doubt the organisation has the spare resources for. However, you can still use the [Nextcloud commandline client](https://docs.nextcloud.com/desktop/2.3/advancedusage.html#nextcloud-command-line-client), this should work without any problems.

**Comment by veddox** [comment]
Turns out, the option to disable the web engine was already discussed (#932) and somebody is working on implementing it (#2204). So there may be hope for X2GO yet :wink:
